use_frameworks!

target 'YYLib_Example' do
  pod 'YYLib', :path => '../'

  target 'YYLib_Tests' do
    inherit! :search_paths

    pod 'Specta'
  pod 'Expecta'
  pod 'FBSnapshotTestCase'
  pod 'Expecta+Snapshots'
  end
end
